name: Build Marlin Firmware

on:
  workflow_dispatch:

jobs:
  build_marlin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Install marlin_auto_build
        run: |
          git clone https://github.com/zisismaras/marlin_auto_build.git
          cd marlin_auto_build
          npm install

      - name: Create output folder
        run: mkdir -p builds

      - name: Build Marlin firmware
        run: |
          cd marlin_auto_build
          node ./lib/runner.js --color --build autoLevel7x7Lin --output ../builds

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: marlin-firmware
          path: builds/
