name: Marlin Auto Build

on:
  push:
    paths:
      - '**.h'
      - '**.cpp'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build_marlin:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Install Node.js (required by marlin_auto_build)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3️⃣ Install Python & PlatformIO
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install PlatformIO
        run: pip install -U platformio

      # 4️⃣ Clone marlin_auto_build and compile it
      - name: Setup Marlin Auto Build
        run: |
          git clone https://github.com/zisismaras/marlin_auto_build.git
          cd marlin_auto_build
          npm install
          npm run build

      # 5️⃣ Create builds folder inside workspace
      - name: Create output folder
        run: mkdir -p builds

      # 6️⃣ Run the Marlin build
      - name: Build Marlin firmware
        run: |
          cd marlin_auto_build
          node ./dist/cli.js --color --build autoLevel7x7Lin --output ../builds

      # 7️⃣ Upload the firmware artifact
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: marlin-firmware
          path: builds/

