name: marlin_auto_build

# Trigger on changes to firmware source or manually
on:
  push:
    paths:
      - '**.h'
      - '**.cpp'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build_marlin:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3️⃣ Install Python & PlatformIO
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install PlatformIO
        run: pip install -U platformio

      # 4️⃣ Install marlin_auto_build
      - name: Install marlin_auto_build
        run: |
          git clone https://github.com/zisismaras/marlin_auto_build.git
          cd marlin_auto_build
          npm install

      # 5️⃣ Compile TypeScript
      - name: Compile marlin_auto_build
        run: |
          cd marlin_auto_build
          npx tsc --build

      # 6️⃣ Create builds folder
      - name: Create output folder
        run: mkdir -p builds

      # 7️⃣ Run the build
      - name: Build Marlin firmware
        run: |
          cd marlin_auto_build
          node ./dist/cli.js --color --build autoLevel7x7Lin --output ../builds

      # 8️⃣ Upload firmware artifacts to GitHub
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: marlin-firmware
          path: builds/
