name: marlin_auto_build

on:
  push:
    paths:
      - '**.h'
      - '**.cpp'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build_marlin:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build Marlin using the prebuilt action
      - name: Build Marlin firmware
        uses: zisismaras/marlin_auto_build@master
        with:
          build: autoLevel7x7Lin
          output: ./builds

      # Upload firmware artifacts
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: marlin-firmware
          path: ./builds/

